# Generated by Django 5.2.4 on 2025-07-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('POS', 'POS'), ('ECOM', 'E-Commerce'), ('TRANSFER', 'Transfer'), ('CASHOUT', 'Cash Out'), ('INTL', 'International Payment')], max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_for_credit_score_above', models.IntegerField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
