# Generated by Django 5.2.4 on 2025-07-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffrule',
            name='applies_to_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
