# Generated by Django 5.2.4 on 2025-07-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_tariffrule_applies_to_international_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffrule',
            name='transaction_type',
            field=models.CharField(choices=[('POS', 'POS'), ('ECOM', 'ECOM'), ('TRANSFER', 'TRANSFER'), ('CASHOUT', 'CASHOUT'), ('INTL', 'INTL')], max_length=20),
        ),
    ]
